# Generated by Django 4.2.1 on 2023-05-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название завода')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('contacts', models.ManyToManyField(to='main.contact', verbose_name='Данные контактов')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель продукта')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя крупной розничной сети')),
                ('debt', models.FloatField(verbose_name='Задолженность перед поставщиком')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('contacts', models.ManyToManyField(to='main.contact', verbose_name='Данные контактов')),
                ('products', models.ManyToManyField(to='main.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя индивидуально предпринимателя')),
                ('debt', models.FloatField(verbose_name='Задолженность перед поставщиком')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('contacts', models.ManyToManyField(to='main.contact', verbose_name='Данные контактов')),
                ('products', models.ManyToManyField(to='main.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.retailchain', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='Продукты'),
        ),
    ]
